// Single entry point for the E2E page objects and shared readbacks, so specs read
// like the manual test script (loadFixtureAsStack, selectPanel, openOperation,
// readPixelValueAt, readMetadata, readHistoryEntries, readRegionStats).

export { loadFixtureAsStack } from "./load-fixture";
export {
  panelGrid,
  panelCell,
  panelCanvas,
  selectPanel,
  countSelectedPanels,
  countPanels,
  clickPanelToSelect,
  expectPanelShowsSelectionRing,
  expectOnlyPanelsSelected,
  clickGridBackgroundToClearSelection,
  type PanelSelectionClickModifiers,
} from "./panels";
export {
  applicationToolbar,
  operationPanel,
  openOperation,
  openOperationFromMenu,
  applyOperation,
  applyOperationInPlace,
  setOpenInNewPanel,
  openInNewPanelSwitch,
  setOperationNumberParameter,
  setOperationEnumParameter,
  cancelOperation,
  isApplyEnabled,
} from "./operations";
export {
  statusBar,
  hoverImagePixel,
  readPixelReadout,
  readPixelValueAt,
  type PixelReadout,
} from "./pixel-readout";
export { metadataSection, readMetadata, type MetadataReadout } from "./metadata-panel";
export {
  historySection,
  historyList,
  historyEntryCount,
  readHistoryEntries,
  type HistoryEntryReadout,
} from "./history-panel";
export {
  regionSection,
  readRegionStats,
  histogramSection,
  histogramCanvas,
  readHistogramActiveBandLabel,
  type RegionStatsReadout,
} from "./stats-panels";
export {
  computeCanvasPointForImagePixelAtFitView,
  type PixelDimensions,
  type CanvasPoint,
} from "./image-pixel-canvas-mapping";
export {
  expectPixelReadoutToEqual,
  expectHistoryToRecordOperation,
  expectMetadataDataTypeAndDimensions,
  type ExpectedPixelValue,
  type ExpectedHistoryEntry,
  type ExpectedMetadata,
} from "./assertions";
export {
  gridLayoutDropdownTrigger,
  gridLayoutOptions,
  openGridLayoutDropdown,
  readOfferedGridLayoutLabels,
  selectGridLayout,
  panelCloseButton,
  expectPanelHoldsFile,
  expectPanelIsEmpty,
  closedPanelsToast,
} from "./grid-layout-controls";
export {
  openPanelContextMenu,
  duplicateMenuItem,
  duplicatePanelViaContextMenu,
  duplicateReplacePicker,
  chooseReplaceTargetPanel,
  confirmReplaceWithChosenTarget,
  cancelReplacePicker,
} from "./duplicate-panel";
export {
  normalizedViewingToggle,
  toggleNormalizedViewing,
  expectNormalizedViewingEnabled,
} from "./normalized-viewing";
export {
  goToBandNumberInput,
  goToBandNumberInputInPanel,
  selectActiveBandNumber,
  selectActiveBandNumberInPanel,
  bandNavigatorStrip,
  expectNoOriginalBandAnnotationBesideBandSlider,
  previousBandButton,
  nextBandButton,
  stepToPreviousBand,
  stepToNextBand,
  bandSliderThumb,
  setActiveBandViaSlider,
} from "./band-navigator";
export {
  panelHeaderLabel,
  readPanelHeaderLabel,
  expectPanelHeaderToName,
  expectPanelHeaderActiveBand,
  expectPanelHeaderNotToName,
} from "./panel-header-label";
export {
  removeBandButton,
  removeBandConfirmationDialog,
  removeDisplayedBand,
  confirmPendingBandRemoval,
  cancelPendingBandRemoval,
  subsetBandsToggleButton,
  subsetBandsEditor,
  openSubsetBandsEditor,
  subsetBandsKeepCheckboxes,
  subsetBandsTypedRangeField,
  typeSubsetBandsRange,
  uncheckSubsetBandRow,
  setSubsetBandsOpenInNewPanel,
  applySubsetBands,
  closeSubsetBandsEditorWithoutApplying,
} from "./band-management";
export {
  spectraPlot,
  spectrumLinePaths,
  liveHoverSpectrumLine,
  pinnedSpectrumLines,
  expectLiveHoverSpectrumVisible,
  expectNoLiveHoverSpectrum,
  expectPinnedSpectrumLineCount,
  pinPixelSpectrum,
  expectSpectrumLineSubpathCount,
  readPinnedSpectrumLinePointXs,
  regionMeanSpectrumEnvelopes,
  expectRegionSpectrumCount,
  regionMeanSpectrumLineWithColor,
  regionSpectrumLegendRows,
  pinnedPixelSpectrumLegendRows,
} from "./spectra-plot";
export {
  enqueueAndTriggerOpenImages,
  openImagesReviewModal,
  openImagesReplaceTargetPicker,
  reviewModalRows,
  reviewModalGroups,
  reviewModalNewStackButton,
  reviewModalGroupModeSelect,
  chooseReviewModalGroupMode,
  readReviewModalGroupModeOptionLabels,
  readReviewModalRowFileNamesInOrder,
  reviewModalRecombineIntoOneStackButton,
  clickReviewModalRecombineIntoOneStack,
  confirmReviewModal,
  cancelReplaceTargetPicker,
  chooseOpenImagesReplaceTargetPanel,
  confirmReplaceTargetPicker,
  openImagesErrorToast,
} from "./open-images-flow";
export {
  readUserFacingTextAndAccessibleNames,
  expectNoUserFacingViewportWording,
  expectNoUserFacingSpatialFilterWording,
  expectNoUserFacingBandWeightingWording,
  expectNoUserFacingFalseColorWording,
  expectNoUserFacingBasicProcessingHyphenWording,
  expectNoUserFacingMsiToolboxWording,
} from "./terminology-sweep";
export {
  writeTemporaryWavelengthStackTiffFixtures,
  writeTemporaryDistinctValueWavelengthBandFixtures,
  DISTINCT_VALUE_BAND_FIXTURE_SIDE,
  writeTemporaryCorruptImageFixture,
  type WavelengthStackFixtureFile,
} from "./temporary-open-images-fixtures";
export {
  writeTemporarySingleBandUint16Tiff,
  type SingleBandTiffRequest,
} from "./temporary-raster-tiff-fixture";
export {
  writeTemporaryMultiBandUint16Tiff,
  type MultiBandTiffRequest,
} from "./temporary-multi-band-tiff-fixture";
export {
  writeTemporaryMultiBandFloat32Tiff,
  type MultiBandFloat32TiffRequest,
} from "./temporary-multi-band-float32-tiff-fixture";
export {
  writeTemporarySingleBandUint8Tiff,
  uint8FixtureValueAt,
  UINT8_FIXTURE_SIDE,
} from "./temporary-uint8-raster-fixture";
export {
  FLAT_FIELD_LABEL,
  FLAT_FIELD_LIGHT_FIELD_LABEL,
  FLAT_FIELD_DARK_FIELD_LABEL,
  flatFieldReferenceField,
  chooseLoadedPanelAsFlatFieldReference,
  chooseFlatFieldReferenceFileThroughDialog,
  flatFieldErrorToast,
} from "./flat-field-operation";
export {
  saveImageFormatPicker,
  saveImageFormatRadioGroup,
  readOfferedSaveImageFormatLabels,
  chooseSaveImageFormat,
  expectSaveImageFormatOptionDisabledWithTooltip,
  expectSaveImageFormatOptionDisclosesNote,
  expectSaveImageFormatOptionHasNoBandDisclosure,
  confirmSaveImageFormat,
  cancelSaveImageFormatPicker,
  exportSelectedStackThroughSaveDialog,
  exportSelectedStackAsPngStackToFolder,
  loadImageFromAbsolutePath,
  createTemporaryExportDirectory,
  type SaveImageExportRequest,
  type SaveImageFolderExportRequest,
} from "./save-image-flow";
export {
  saveProjectBundleThroughSaveDialog,
  openProjectBundleThroughOpenDialog,
  createTemporaryProjectBundleDirectory,
  type SaveProjectBundleRequest,
  type OpenProjectBundleRequest,
} from "./project-bundle-flow";
export {
  linkPanZoomMenuItem,
  unlinkPanZoomMenuItem,
  openPanelContextMenuAtCorner,
  linkPanZoomFromPanelContextMenu,
  linkedPanelBadge,
  expectPanelIsLinked,
  expectPanelIsNotLinked,
  differentSizeLinkErrorToast,
  LINK_PAN_ZOOM_MULTI_SELECT_HINT,
  linkPanZoomMenuItemWithHint,
  expectLinkPanZoomMenuItemIsDisabledWithHint,
} from "./linked-panels";
export {
  regionToolButton,
  activateRegionTool,
  ensureRegionToolInactive,
  panelCanvasCenter,
  pagePointForImagePixelCenter,
  pixelsPerImagePixelVertically,
  dragMouseFromTo,
  drawInspectionRoiBetweenPixels,
  readCommittedRoiOverlayRect,
  wheelAtPagePoint,
  readReadoutAtPagePoint,
  resetViewWithDoubleClick,
  type ImagePixel,
  type CanvasRect,
} from "./viewport-navigation";
export {
  operationRegionPlaceholder,
  selectOperationRegionButton,
  expectOperationAwaitsItsOwnRegion,
  selectOperationRegionByDrag,
  type OperationRegionDragRequest,
} from "./operation-region-picker";
export {
  committedRoiBorderRects,
  committedRoiCornerHandleRects,
  expectExactlyOneCommittedRoi,
  expectNoCommittedRoiMarkers,
  plainClickImagePixel,
} from "./roi-inspection";
export {
  FULL_STACK_SCOPE_LABEL,
  BAND_WISE_SCOPE_LABEL,
  SHARED_SCOPE_OPTION_LABELS,
  scopeFieldset,
  scopeOptionRadios,
  scopeOptionRadio,
  expectScopeControlOffersExactlyTheSharedTwoOptions,
  selectFullStackScope,
  selectBandWiseScopeForBands,
} from "./cube-scope-control";
export {
  APPLY_SCOPE_GROUP_NAME,
  WHOLE_STACK_SCOPE_LABEL,
  REGION_OF_INTEREST_SCOPE_LABEL,
  FULL_IMAGE_SCOPE_LABEL,
  applyScopeFieldset,
  applyScopeRadio,
  selectFullImageScope,
  selectRegionOfInterestScope,
  selectWholeStackScope,
} from "./apply-scope-control";
export {
  TONE_CURVE_LABEL,
  toneCurveEditorHistogramCanvas,
  toneCurveEndpointHandles,
  toneCurveInteriorHandles,
  toneCurveAllHandles,
  selectedToneCurveAnchorHandles,
  expectExactlyOneToneCurveAnchorSelected,
  expectToneCurveHandleIsSelected,
  clickToneCurveAnchorHandle,
  expectToneCurveOpensWithTwoEndpoints,
  addToneCurveAnchorAtFraction,
  dragToneCurveEndpointTo,
  readToneCurveAnchors,
  toneCurveAnchorField,
  readToneCurveAnchorFieldValue,
  setToneCurveAnchorField,
  stepToneCurveAnchorField,
  nudgeSelectedToneCurveAnchor,
  deleteSelectedToneCurveAnchor,
  toneCurveResetButton,
  clickToneCurveResetToIdentity,
  toneCurveReferenceGrid,
  toneCurveReferenceGridLines,
  expectToneCurveReferenceGridIsPresent,
  toneCurveChannelSelector,
  toneCurveChannelButton,
  selectToneCurveChannel,
  expectToneCurveChannelSelectorPresent,
  expectToneCurveChannelSelectorAbsent,
  expectToneCurveChannelIsActive,
  expectToneCurveHistogramBackdrop,
  toneCurveEditingBandLabel,
  readToneCurveEditingBandLabel,
  type ToneCurveValueRanges,
  type ToneCurveAnchorPoint,
  type ToneCurveAnchorFieldLabel,
  type ToneCurveNudgeDirection,
  type ToneCurveChannelButtonName,
  type ToneCurveChannelBackdropName,
} from "./tone-curve-editor";
export {
  summarizeCanvasPixels,
  nonClearPixelFraction,
  averageNonClearCanvasColor,
  colorfulNonClearPixelFraction,
  saturatedWhitePixelFraction,
  type CanvasPixelSummary,
  type CanvasAverageColor,
} from "./canvas-pixels";
export {
  THRESHOLD_OPERATION_LABEL,
  thresholdBoundHandle,
  thresholdBoundField,
  thresholdMethodSelect,
  selectThresholdMethod,
  expectThresholdEditorReady,
  expectThresholdBoundsEditorAbsent,
  setThresholdBoundField,
  readThresholdBoundFieldValue,
  dragThresholdBoundHandleToFraction,
  releaseThresholdBoundDrag,
  type ThresholdBoundSide,
  type ThresholdMethodLabel,
} from "./threshold-editor";
export {
  readImageTextureUploadCount,
  readPreviewRasterAllocationCount,
} from "./render-instrumentation";
export {
  BRIGHTNESS_CONTRAST_LABEL,
  BRIGHTNESS_SLIDER_LABEL,
  CONTRAST_SLIDER_LABEL,
  brightnessContrastSliderThumb,
  setBrightnessContrastSlider,
  maximizeBrightnessContrastSlider,
  setLogSymmetricContrastSlider,
  contrastRatioAtSliderPosition,
  contrastSliderDisplayedValue,
  applyToAllBandsSwitch,
  setApplyToAllBands,
} from "./brightness-contrast-controls";
export {
  ROTATE_LABEL,
  REFLECT_LABEL,
  geometricTransformOperationLabel,
  geometricTransformSelect,
  readOfferedGeometricTransformLabels,
  selectGeometricTransform,
  openGeometricTransformFromMenu,
  applyGeometricTransformInPlace,
  quickTransformToolbarButton,
  applyQuickGeometricTransform,
  type GeometricTransformChoice,
  type QuickGeometricTransformChoice,
} from "./geometric-transform-operation";
export {
  FIXED_RIGHT_PANEL_SECTION_ORDER,
  rightPanel,
  rightPanelSections,
  readRightPanelSectionLabelsInOrder,
  expectRightPanelSectionsInFixedOrder,
  expectNoRemovedRightPanelSections,
} from "./right-panel-sections";
export {
  histogramValueAxisLabelsColumn,
  histogramCountAxisLabelsColumn,
  readHistogramValueAxisLabels,
  readHistogramCountAxisLabels,
  readSpectraPlotAxisLabels,
  readAllChartAxisLabels,
  expectLabelsUseSuperscriptNotMachineNotation,
  expectLabelsCoverLargeAndSmallSuperscripts,
  expectAxisLabelIsSuperscriptCount,
} from "./chart-axis-labels";
export {
  readHistogramMidRowProfile,
  expectHistogramBarsMeetWithoutGaps,
  expectHistogramShowsEmptyMiddleBins,
  type HistogramRowProfile,
} from "./histogram-bar-canvas";
export {
  BAND_WEIGHTING_OPERATION_LABEL,
  bandWeightField,
  expectBandWeightingEditorReady,
  setBandWeightField,
  clickResetAllWeightsToOne,
  clickResetAllWeightsToZero,
  runBandWeightingFormula,
  clickImportBandWeightingScript,
  expectBandWeightFieldsToEqual,
} from "./band-weighting";
export {
  BAND_SELECTION_OPERATION_LABEL,
  applyBandSelectionFunction,
  bandSelectionFormulaField,
  bandSelectionFunctionSegment,
  expectBandSelectionEditorReady,
  expectBandSelectionToolLoaded,
  clickBandSelectionPreset,
  enterBandSelectionFormula,
  importBandSelectionScript,
  importBandSelectionScriptButton,
  openBandSelectionFunctionEditor,
  subsetBandsModeSelect,
} from "./band-selection";
export {
  DUPLICATE_BANDS_OPERATION_LABEL,
  openSubsetBandsDuplicateEditor,
  subsetBandsDuplicateField,
  typeSubsetBandsDuplicateRange,
} from "./duplicate-bands";
export {
  applyCustomTransformAwaitingRun,
  clickImportCustomTransformScript,
  CUSTOM_TRANSFORM_FORMULA_SET_STATUS,
  CUSTOM_TRANSFORM_OPERATION_LABEL,
  customTransformFailureToast,
  expectCustomTransformConfigured,
  expectCustomTransformEditorReady,
  expectCustomTransformPanelClosed,
  expectCustomTransformPanelStillOpen,
  loadedToolStatusText,
  setCustomTransformFormula,
} from "./custom-transform";
export {
  addMaskCategoriesUntilTheControlDisables,
  addMaskCategoryButton,
  closeMasksOptions,
  createMaskLayer,
  maskCategoryNameField,
  maskCategoryNameFields,
  maskLayerNameField,
  maskLayerOpacitySlider,
  maskLayerOptions,
  masksOptionsPanel,
  masksRemovedToast,
  MASKS_REMOVED_TOAST_TEXT,
  MASKS_TOOL_LABEL,
  MAX_MASK_CATEGORIES,
  openMasksOptions,
  renameMaskCategory,
} from "./masks-panel";
export {
  enableMaskEraser,
  maskBrushCategoryOption,
  maskBrushSizeSlider,
  maskEraserToggle,
  paintMaskDotAtPagePoint,
  paintMaskStrokeBetweenPixels,
  selectMaskBrushCategory,
  setMaskBrushSizeToOnePixel,
} from "./mask-brush";
export {
  decodeIndexPngInsideMaskZip,
  decodeSingleChannelPngBuffer,
  exportMaskButton,
  exportSelectedMaskAndDecodeIndexPng,
  exportSelectedMaskToZipPath,
  findMaskZipSidecarStemOrThrow,
  importMaskButton,
  importMaskFromPath,
  maskToastContaining,
  type DecodedMaskIndexPng,
} from "./mask-file-transfer";
export { listZipEntryNames, readZipEntriesByName } from "./zip-archive";
export {
  chooseCnrBackgroundCategory,
  chooseCnrTextCategory,
  cnrBackgroundCategoryPicker,
  cnrComputeButton,
  cnrMaskLayerPicker,
  cnrOptionsPanel,
  cnrScorePlot,
  cnrScoresSection,
  cnrTextCategoryPicker,
  cnrTopBandRows,
  computeCnrScores,
  readCnrTopBandRows,
  CNR_NOT_COMPUTED_TEXT,
  CNR_PANEL_LABEL,
  type CnrTopBandRowReadout,
} from "./cnr-panel";
export {
  computeNpcScores,
  expectScoreWithinRelativeTolerance,
  npcBinsField,
  npcComputeButton,
  npcMaskLayerPicker,
  npcOptionsPanel,
  npcScorePlot,
  npcScoresSection,
  npcTopBandRows,
  readNpcTopBandRows,
  NPC_NOT_COMPUTED_TEXT,
  NPC_PANEL_LABEL,
  setNpcBinCount,
  type NpcTopBandRowReadout,
} from "./npc-panel";
export {
  chooseRopObjective,
  importRopObjectiveScript,
  pressNewProjectionUntilProjectionReady,
  pressNewProjectionUntilScoreShows,
  pressNewProjectionUntilSeedShows,
  ropBestScoreReadout,
  ropCnrBackgroundCategoryPicker,
  ropCnrTextCategoryPicker,
  ropKeepBestButton,
  ropKeepButton,
  ropNewProjectionButton,
  ropObjectivePicker,
  ropOptionsPanel,
  ropPinnedPanelReadout,
  ropProjectionCountField,
  ropScoreReadout,
  ropSearchButton,
  ropSeedReadout,
  ROP_NO_CANDIDATE_TEXT,
  ROP_PANEL_LABEL,
  ROP_PRESS_REFUSED_TEXT,
  ROP_PROJECTION_READY_TEXT,
  setForcedRopSeed,
  setRopProjectionCount,
  startRopProjectionSearch,
} from "./rop-panel";
export { enqueueOpenDialogPaths } from "./dialog-stub-controls";
export { reimportPanelSourceFromDisk, reimportSuccessToast } from "./reimport-source";
export {
  noQualifyingThresholdResultHint,
  promoteFirstQualifyingThresholdResult,
  promoteThresholdResultButton,
  promoteThresholdResultSection,
  sourceBandMenuTrigger,
  sourcePanelMenuTrigger,
} from "./mask-threshold-promotion";
